Точность и спад урона
stalker14-project/stalker-14 pull request #188
Opened 2024-12-19 16:06 UTC by wCATw

## Что я изменил
Я перенес систему точности, уклонения и спада урона с билда RMC-14. 
Также я изменил для теста некоторые прототипы.

## Убедитесь что вы проверили и согласны со следующим
- [X] Да, я запустил свой код и протестил что изменения работают
- [X] Да, я проверил что в консольном выводе клиента и сервера не появилось ошибок после моих изменений
- [X] Я согласен, что отправляя PR соглашаюсь на условия лицензии [Лицензия](https://github.com/stalker14-project/stalker-14/edit/master/LICENSE.TXT).
- [X] Я проверил и подтверждаю, что все картинки и аудио файлы которые я добавил в PR принадлежат мне или находятся под открытой лицензией

## TODO
Записать кредитс билда RMC и указать автора оригинала.
Изменить значения компонентов в прототипах.

Вот структура для прототипов:
\*ЛОГИКА - логичесоке значение (true/false)
\*ЧИСЛО - целочисленное значение
\*ПЛАВ\_ЧИСЛО - числовое значение с десятичной дробью
# 5 новых компонентов
## на снаряды [Projectile]
- Точность [**STProjectileAccuracy**]
  - параметр __thresholds__ заполняется по шаблону ниже
  - параметр __accuracy__: ЧИСЛО
  - параметр  __ignoreFriendlyEvasion__: ЛОГИКА
```yaml
thresholds:
- range: ПЛАВ_ЧИСЛО
  falloff: ЧИСЛО
```
- Спад урона [**STProjectileDamageFalloff**]
  - параметр __thresholds__ заполняется по шаблону ниже
```yaml
thresholds:
- range: ПЛАВ_ЧИСЛО
  falloff: ЧИСЛО
  ignoreModifiers: ЛОГИКА
```
## на оружие [Weapon/Gun]
- Точность [**STWeaponAccuracy**]
  - параметр __accuracyMultiplier__: ЧИСЛО
  - параметр __accuracyMultiplierUnwielded__: ЧИСЛО
- Спад урона [**STWeaponDamageFalloff**]
  - параметр __falloffMultiplier__: ЧИСЛО
## на существ [Species/Mobs]
- Размер [**STSize**]
  - параметр __size__: значение из перечня Small, Humanoid, VerySmallMutant, SmallMutant, Mutant, Big, Immobile

2024-12-19 16:17 UTC, JerryImMouse submitted a review, later dismissed
По стилю и чистоте ниче не скажу, ахуенно. А вот в логику лезть не буду, даже не просите

2025-01-13 05:16 UTC, Tornado-Technology commented
@JerryImMouse ало, у нас компоненты с ST начинаются.

2025-01-13 05:20 UTC, Tornado-Technology requested changes
Я пока не решусь сделать полное ревью, очень громоздкая система, где все ещё вшито много бесполезных или сломанных механик. По всем вопросам трогать меня в дискорде.

2025-01-13 05:20 UTC, Tornado-Technology commented on Content.Shared/_Stalker/Evasion/EvasionComponent.cs
> +    public FixedPoint2 Evasion = 0;
Разъеби лопатой эту хуйню, тут нормально бы смотрелись флоаты

2025-01-13 05:20 UTC, Tornado-Technology commented on Content.Shared/_Stalker/Evasion/EvasionComponent.cs
> +    Rest = -15,
Чисто RMC хуйня у нас такого нет

2025-01-13 05:20 UTC, Tornado-Technology commented on Content.Shared/_Stalker/Evasion/EvasionComponent.cs
> +    Invisibility = 1000,
Кровососы выебут тебя в очко

2025-04-29 13:43 UTC, ILReact commented
Стрельба стала более косой с этой механикой

2025-07-11 09:15 UTC, closed without merging